name: reddit_env
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - numpy
  - pandas
  - praw
  - nltk
  - spacy=3.5.0
  - transformers
  - tensorflow
  - boto3
  - pip
  - pytorch
  - torchvision
  - pip:
    - contractions
    - emoji
